# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Login

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Then'
  pod 'AppCenter'

  target 'RxSwift-LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-LoginUITests' do
    # Pods for testing
  end

end
